server:
  port: 9999

  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

  tomcat:
    basedir: . # access log를 저장할 base directory 지정
    accesslog:
      enabled: true # access log 저장 여부 (default: false)
      directory: logs # access log를 저장할 상세 directory (base directory에 기반한) (default: logs)
      pattern: '%h %l %u %t "%r" %s %b %D' # access log 출력 패턴
      prefix: access # access log 파일이름 prefix
      suffix: .log # access log 파일이름 suffix (확장자 포함)
      rotate: true # access log rotation 여부
      rename-on-rotate: true # rotation 시, 새로운 이름 지정 여부 (rotate 될 때의 날짜명이 로그 파일이름에 찍힘)
    threads:
      max: 200
spring:
  profiles:
    active:
      - develop
    group:
      develop: "env"

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    #    org.hibernate.SQL: debug
    #    org.hibernate.type: trace
    org:
      springframework: INFO
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    path: logs
  logback:
    rollingpolicy:
      file-name-pattern: Log-%d{yyyy-MM-dd}.%i.log

springdoc:
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.ddockddack.domain
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
